Re-add appveyor CI
- partially undo commit b1539152655d6f35c24b5c1066a4afc26d222dbe
(at least temporarily until Github Action workflow is figured out for Windows)

- Github Action workflow fails on Windows but not macOS and ubuntu
* error messages are of the form "C:\rtools40\mingw32\bin\nm.exe: file.o: file format not recognized" where "file" is a SOILWAT2 file
* this then leads to "undefined reference to XXX" where "XXX" is a SOILWAT2 object

- testing on r-hub doesn't currently work because an old version of the "remotes" package is installed ('remotes_2.1.1.9000.tar.gz') which attempts to download from the "master" branch -- instead of from the default branch ("main" for rSW2-related packages) as implemented with remotes v2.2.0 (July 2020)

- the last release of rSOILWAT2 (v4.0.4, March 2021) checked correctly on appveyor