Fix `validity` method for "swMarkov"
- tests for "R-devel" failed because of
>  Fatal error: length > 1 in coercion to logical

- this was caused because `temp == c(0, 0)` returned a length-2 vector
--> replaced `==` with `identical()`