Attempt to fix appveyor yaml
Problem: "
package 'curl' successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package 'curl'
Execution halted
Command exited with code 1
"

--> maybe because I installed circular and rSW2utils in the "install" step instead in the "build_script" one?